version: '3'

services:
  postgres:
    image: 'postgres:16'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRE_DB=itclinic'

  app:
    build: ./
    container_name: 'java-backend'
    ports:
      - 6560:8080